title: Sensei of code
author: Jerome E
email: marry-me@snailmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a one-stop destination for all things food. Come and have an eye-opening --rather mouth-watering read as I peel open secrets behind the various delicacies from far and near(and here too).

# social links
twitter_username: jerome_engena # DO NOT include the @ character, or else the build will fail!
github_username:  JeromeEngena # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
